stages:
 - quality
 - build
 - test

syntax:
  stage: quality
  image: 'registry.gitlab.satellogic.com/joac/docker-fades-make-builder:latest'
  script:
    - fades -p python3 -d flake8 -x flake8 
  tags:
    - docker-amd64-v2

no_pyc:
  stage: quality
  image: 'registry.gitlab.satellogic.com/joac/docker-fades-make-builder:latest'
  script:
    - exit $(find * -name *.pyc -o -name *.pycache | wc -l)
  tags:
    - docker-amd64-v2

test:
  stage: test
  image: 'registry.gitlab.satellogic.com/joac/docker-fades-make-builder:latest'
  script:
    - fades -d numpy -d hypothesis -x python3 -m unittest -v
  tags:
    - docker-amd64-v2
